FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY servicio_pb2.py .
COPY servicio_pb2_grpc.py .
COPY cliente.py .

CMD ["python", "cliente.py", "1"]