# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'servicio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservicio.proto\x12\x08servicio\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x0cItemResponse\x12\x12\n\nencontrado\x18\x01 \x01(\x08\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rrera\x18\x03 \x01(\t2M\n\rServicioItems\x12<\n\x0bObtenerItem\x12\x15.servicio.ItemRequest\x1a\x16.servicio.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=28
  _globals['_ITEMREQUEST']._serialized_end=53
  _globals['_ITEMRESPONSE']._serialized_start=55
  _globals['_ITEMRESPONSE']._serialized_end=122
  _globals['_SERVICIOITEMS']._serialized_start=124
  _globals['_SERVICIOITEMS']._serialized_end=201
# @@protoc_insertion_point(module_scope)
