# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\"\x1c\n\x0eGetDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"M\n\x0fGetDataResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0f\n\x07\x63\x61rrera\x18\x04 \x01(\t2E\n\x0b\x44\x61taService\x12\x36\n\x07GetData\x12\x14.data.GetDataRequest\x1a\x15.data.GetDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDATAREQUEST']._serialized_start=20
  _globals['_GETDATAREQUEST']._serialized_end=48
  _globals['_GETDATARESPONSE']._serialized_start=50
  _globals['_GETDATARESPONSE']._serialized_end=127
  _globals['_DATASERVICE']._serialized_start=129
  _globals['_DATASERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
