# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'servicio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservicio.proto\"\x1c\n\x0eUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"_\n\x0fUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0f\n\x07materia\x18\x03 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x04 \x01(\t\x12\x0f\n\x07\x63\x65lular\x18\x05 \x01(\t2E\n\x0eUsuarioService\x12\x33\n\x0eObtenerUsuario\x12\x0f.UsuarioRequest\x1a\x10.UsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIOREQUEST']._serialized_start=18
  _globals['_USUARIOREQUEST']._serialized_end=46
  _globals['_USUARIORESPONSE']._serialized_start=48
  _globals['_USUARIORESPONSE']._serialized_end=143
  _globals['_USUARIOSERVICE']._serialized_start=145
  _globals['_USUARIOSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
