FROM node:22-alpine
WORKDIR /app
COPY package*.json ./

#Dependencias
RUN npm install

# Copiar todo el código fuente y archivos proto
COPY . .

#Puertos para REST (3000) y gRPC (50051)
EXPOSE 3000
EXPOSE 50051

#Iniciar servidor
CMD ["node", "server/main.js"]
