FROM python:3.10-slim

WORKDIR /app

COPY service.proto .
COPY app_grpc.py .

RUN pip install grpcio grpcio-tools

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto

EXPOSE 50051

CMD ["python", "app_grpc.py"]