# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08producto\"\x1d\n\x0fProductoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x14\x43rearProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x02\"M\n\x10ProductoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xa8\x01\n\x0fProductoService\x12H\n\x0fObtenerProducto\x12\x19.producto.ProductoRequest\x1a\x1a.producto.ProductoResponse\x12K\n\rCrearProducto\x12\x1e.producto.CrearProductoRequest\x1a\x1a.producto.ProductoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOREQUEST']._serialized_start=27
  _globals['_PRODUCTOREQUEST']._serialized_end=56
  _globals['_CREARPRODUCTOREQUEST']._serialized_start=58
  _globals['_CREARPRODUCTOREQUEST']._serialized_end=112
  _globals['_PRODUCTORESPONSE']._serialized_start=114
  _globals['_PRODUCTORESPONSE']._serialized_end=191
  _globals['_PRODUCTOSERVICE']._serialized_start=194
  _globals['_PRODUCTOSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
