# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"#\n\x0bSumaRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"!\n\x0cSumaResponse\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32H\n\nCalculator\x12:\n\x05Sumar\x12\x17.calculator.SumaRequest\x1a\x18.calculator.SumaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMAREQUEST']._serialized_start=32
  _globals['_SUMAREQUEST']._serialized_end=67
  _globals['_SUMARESPONSE']._serialized_start=69
  _globals['_SUMARESPONSE']._serialized_end=102
  _globals['_CALCULATOR']._serialized_start=104
  _globals['_CALCULATOR']._serialized_end=176
# @@protoc_insertion_point(module_scope)
