version: '3.8'

services:
  # 1. Config Server Replica Set
  configsvr:
    image: mongo:6.0
    container_name: mongo-config
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - "27019:27019"

  # 2. Shard 1
  shard1:
    image: mongo:6.0
    container_name: mongo-shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    ports:
      - "27018:27018"

  # 3. Shard 2
  shard2:
    image: mongo:6.0
    container_name: mongo-shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27016:27017"

  # 4. Router mongos
  mongos:
    image: mongo:6.0
    container_name: mongo-mongos
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2