# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x04item\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"W\n\x0cItemResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0c\n\x04tipo\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x05 \x01(\x08\x32?\n\x0bItemService\x12\x30\n\x07GetItem\x12\x11.item.ItemRequest\x1a\x12.item.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=20
  _globals['_ITEMREQUEST']._serialized_end=45
  _globals['_ITEMRESPONSE']._serialized_start=47
  _globals['_ITEMRESPONSE']._serialized_end=134
  _globals['_ITEMSERVICE']._serialized_start=136
  _globals['_ITEMSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
