# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08servicio\"\x1b\n\rBuscarRequest\x12\n\n\x02id\x18\x01 \x01(\t\"O\n\x0e\x42uscarResponse\x12\x12\n\nencontrado\x18\x01 \x01(\x08\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x32G\n\x08\x43onsulta\x12;\n\x06\x42uscar\x12\x17.servicio.BuscarRequest\x1a\x18.servicio.BuscarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSCARREQUEST']._serialized_start=27
  _globals['_BUSCARREQUEST']._serialized_end=54
  _globals['_BUSCARRESPONSE']._serialized_start=56
  _globals['_BUSCARRESPONSE']._serialized_end=135
  _globals['_CONSULTA']._serialized_start=137
  _globals['_CONSULTA']._serialized_end=208
# @@protoc_insertion_point(module_scope)
