services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      db_reto_dev:
        condition: service_healthy
      db_reto_prod:
        condition: service_healthy

  db_reto_dev:
    image: postgres:17-alpine
    env_file: .env
    volumes:
      - datos_reto_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  db_reto_prod:
    image: postgres:17-alpine
    env_file: .env.prod
    volumes:
      - datos_reto_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  cache:
    image: redis:8-alpine

  broker:
    image: rabbitmq:4-management-alpine
    ports:
      - "15672:15672"

volumes:
  datos_reto_dev:
  datos_reto_prod:
