FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Generar las clases de gRPC a partir del .proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. servicio.proto
EXPOSE 8000 50051
CMD ["python", "servidor.py"]