FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY logica.py server_rest.py ./
EXPOSE 3000
CMD ["python", "server_rest.py", "runserver", "0.0.0.0:3000"]