FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY cliente.py servicio.proto ./
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. servicio.proto
CMD ["python", "cliente.py"]