version: '3.8'

services:
  hybrid-service:
    build: .
    container_name: t01_service
    ports:
      - "8000:8000"
      - "50051:50051"
    networks:
      - t01-network

networks:
  t01-network:
    driver: bridge