# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04item\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"L\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x32?\n\x0bItemService\x12\x30\n\x07GetItem\x12\x11.item.ItemRequest\x1a\x12.item.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMREQUEST']._serialized_start=23
  _globals['_ITEMREQUEST']._serialized_end=48
  _globals['_ITEMRESPONSE']._serialized_start=50
  _globals['_ITEMRESPONSE']._serialized_end=126
  _globals['_ITEMSERVICE']._serialized_start=128
  _globals['_ITEMSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
