FROM python:3.12-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1

COPY requirements-cliente.txt .
RUN pip install --no-cache-dir -r requirements-cliente.txt

COPY catalogo.proto cliente.py medicion.py prueba_grpc.py ./
RUN python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. catalogo.proto

CMD ["python", "-u", "cliente.py"]
