# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import servicio_pb2 as servicio__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in servicio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuscadorServiceStub:
    """Definición del servicio y sus métodos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Consultar = channel.unary_unary(
                '/servicio.BuscadorService/Consultar',
                request_serializer=servicio__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=servicio__pb2.ConsultaResponse.FromString,
                _registered_method=True)


class BuscadorServiceServicer:
    """Definición del servicio y sus métodos
    """

    def Consultar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuscadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Consultar': grpc.unary_unary_rpc_method_handler(
                    servicer.Consultar,
                    request_deserializer=servicio__pb2.ConsultaRequest.FromString,
                    response_serializer=servicio__pb2.ConsultaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servicio.BuscadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servicio.BuscadorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuscadorService:
    """Definición del servicio y sus métodos
    """

    @staticmethod
    def Consultar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servicio.BuscadorService/Consultar',
            servicio__pb2.ConsultaRequest.SerializeToString,
            servicio__pb2.ConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
