FROM python:3.9-slim
WORKDIR /app
RUN pip install requests grpcio grpcio-tools
COPY . .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto
CMD ["python", "client.py"]
