# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'servicio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservicio.proto\x12\x08servicio\"\x1d\n\x0f\x43onsultaRequest\x12\n\n\x02id\x18\x01 \x01(\t\"G\n\x10\x43onsultaResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0binformacion\x18\x02 \x01(\t\x12\x12\n\nencontrado\x18\x03 \x01(\x08\x32U\n\x0f\x42uscadorService\x12\x42\n\tConsultar\x12\x19.servicio.ConsultaRequest\x1a\x1a.servicio.ConsultaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTAREQUEST']._serialized_start=28
  _globals['_CONSULTAREQUEST']._serialized_end=57
  _globals['_CONSULTARESPONSE']._serialized_start=59
  _globals['_CONSULTARESPONSE']._serialized_end=130
  _globals['_BUSCADORSERVICE']._serialized_start=132
  _globals['_BUSCADORSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
