FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir grpcio grpcio-tools requests

COPY . .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto

CMD ["python", "client.py"]